### ISSUE TITLE
Make accessible

### ISSUE THREAD

**Issue by batpigandme** [rstudio/hugo-graphite#15]
Realizing a lot of the changes in the issue I opened for tidyverse.org (https://github.com/tidyverse/tidyverse.org/issues/374) should probably be made here.

Accessibility evaluation:
* Landing page https://wave.webaim.org/report#/https://tourmaline.netlify.com/
* Blog layout https://wave.webaim.org/report#/https://tidyverse.org/blog (I can't find this in the template site)

**Comment by batpigandme** [comment]
Also related to https://github.com/rstudio/hugo-tourmaline/pull/22 (not sure why that build isn't working, since it's erroring out on pages I didn't touch)

**Comment by apreshill** [comment]
Hey @batpigandme - thanks! I have no problem with adding the aria hidden. I'd like to have some more time to think about research removing the links from the images entirely- I'm not sure if the accessibility flags take into account redundant text links (as in, the image isn't the only way to click).

**Comment by batpigandme** [comment]
The flags are actually _because_ the links are redundant, I think. But I'm totally open to whatever you find.

**Comment by apreshill** [comment]
@batpigandme I hope https://github.com/rstudio/hugo-graphite/releases/tag/v1.0.0 took care of many of these issues! Let us know if not and we can re-open.

Demo site:
https://hugo-graphite.netlify.app/
