### ISSUE TITLE
add tags

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-graphite#20]
https://github.com/tidyverse/tidyverse.org/issues/185

Code to add to single layout file: 

https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template

A version for tidymodels.org worked here:

https://github.com/tidymodels/tidymodels.org/blob/master/layouts/start/single.html#L16-L25

**Comment by dcossyleon** [comment]
@apreshill Here's the current styling I'm using for tags
![image](https://user-images.githubusercontent.com/29008894/85909389-96969200-b7e7-11ea-8242-10f9f3de9951.png)
