### ISSUE TITLE
Disable horizontal scroll

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-graphite#31]
Seen here:

https://www.tidymodels.org/start/resampling/#intro
```
/*---fix code scrolling-- */
pre {
  white-space: pre-wrap;
}
```

**Comment by dcossyleon** [comment]
https://github.com/rstudio/hugo-tourmaline/pull/43/commits/2064e0c3a22789dc8176ce3aeac98aabf356d09d

This should fix it once it's merged in
