### ISSUE TITLE
Demo site css upgrade

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-graphite#35]
<img width="1404" alt="Screen Shot 2020-04-15 at 1 29 12 PM" src="https://user-images.githubusercontent.com/12160301/82132023-406a1400-9790-11ea-9cbe-89b870eb6b3b.png">

```
#rStudioHeader .productName {
	color: #4254A7;
}

div.tagline {
	font-family: 'Libre Baskerville', serif !important;
	text-transform: uppercase;
	font-size: 1.2rem !important;
	font-weight: bold;
	letter-spacing: 2px;
}

#rStudioHeader #menu .menuItem:hover {
	background-color: white;
	color: #4254A7;
}

#TableOfContents a {
	font-family: 'Libre Baskerville';
	color: #00000075;
	transition: color 0.3s;
	font-size: 15px;
}

.sectionTitle, .sectionTitle a {
	text-transform: uppercase;
	letter-spacing: 2pt;
	font-size: 0.8rem !important;
	font-weight: bold;
	color: #4254A7;
}

h1, .article-title {
	font-family: 'Libre Baskerville', serif;
	color: #4254A7;
	font-weight: bold;
	font-size: 2em;
}

h2 {
	font-family: 'Libre Baskerville', serif;
	font-weight: bold;
	font-size: 1.25em;
}

.article-content ul li::before {
	content: "\2022";
	color: #f6b73c;
	font-weight: bold;
	display: inline-block;
	width: 1.5em;
	margin-left: -1.7em;
}

#rStudioFooter.band {
	background-color: #4254a730;
}
```
Many of these will need to be added to params.toml

**Comment by dcossyleon** [comment]
@apreshill: So should I add create new params in[`../exampleSite/config/_default/params.toml`](https://github.com/rstudio/hugo-tourmaline/blob/master/exampleSite/config/_default/params.toml) but then add the appropriate CSS to this file to [`../layouts/partials/custom-site.css`](https://github.com/rstudio/hugo-tourmaline/blob/master/layouts/partials/custom-site.css)?

**Comment by apreshill** [comment]
Exactly!
https://github.com/rstudio/hugo-tourmaline/blob/master/exampleSite/config/_default/params.toml#L61-L64

```
# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
```

**Comment by dcossyleon** [comment]
Is there a way to add these new params in such a way that it won't cause a bunch of breaking changes if a site using this theme leaves the new params blank?

I'm envisioning something a conditional like "if X params are blank, then don't apply X style rules in custom-site.css"
