### ISSUE TITLE
Copy two new content sections from tidymodels.org

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-graphite#36]
1. Tutorial (this is "Get started")

1. Learn (this is "Learn")

Needs:

- content added to the example site

- layout files

- CSS

**Comment by dcossyleon** [comment]
https://github.com/rstudio/hugo-tourmaline/pull/43/commits/a14928e400043a6da82bb0e8fc6a2be0bbce1373?file-filters%5B%5D=.html , https://github.com/rstudio/hugo-tourmaline/pull/43/commits/2f796d9bc4249f31bdee0a1665485c7b953d4d1d, and https://github.com/rstudio/hugo-tourmaline/pull/43/commits/282de545cc67ce9ff487e8bb4dcc412f3b98f7ff should take care of this
