### ISSUE TITLE
Hexes

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-graphite#40]
Add knob in config file to choose thick or thin hexes, then add parameter for color. Hexes will be 2 different svg files, but color can be a Hugo variable.

**Comment by apreshill** [comment]
@dcossyleon add svg files for thin hexes

**Comment by dcossyleon** [comment]
Going to table the parameterizing of the colors for now. Figuring out a hugo way to parameterize the color codes inside of the .SVG file (and not an HTML file) seemed nontrivial
