### ISSUE TITLE
Finishing touches for theme upgrade

### ISSUE THREAD

**Issue by dcossyleon** [rstudio/hugo-graphite#45]
- [x] Update name to hugo-graphite (+ add @dcossyleon as author in `theme.toml`)
- [x] Include description of new features in README (new layout types, shortcodes)
- [x] Why does copy to clipboard not work for tidyverse site?
- [x] Superscript CSS to main-site.CSS
- [x] Bonus: add pagination CSS for active page on blog
- [x] Why do tidyverse.org blog images still use `background-image:`
- [x] Specify an off-black color for body as a default, just in case
- [x] Give blog square thumbnails wider margin-right
- [x] Tidyverse blog TOC is showing level 3 headers ?? (https://tidyverse-theme-test.netlify.app/blog/2019/11/tidyverse-1-3-0/) *Need to update tidyverse `config.toml`*
- [x] Single pages for authors using background images
- [x] Formatting for "Meet the Team" list page on Edu site is messed up
- [x] Blog list page images on Edu page using background images

PRs needed: 
* Remove tidyverse.org single.html file to *not* use background-image
* Remove tidyverse.org CSS hacks 
* Update tidyverse config.toml for TOC depth 2
* Fix tidyverse blog post image [here](https://www.tidyverse.org/blog/2020/04/self-cleaning-test-fixtures/)
* Fix H2 on sites with packages page, so that markdown handles it, not hardcoded HTML (b409606)

**Comment by apreshill** [comment]
New & improved features:

- [ ] gains sticky TOC for blog posts

- [ ] gains copy-to-clipboard for code chunks

- [ ] gains anchorized header links

- [ ] gains new shortcodes

- [ ] gains 2 new layout types

- [ ] better image accessibility + larger base font sizes

- [ ] more parameters for site customization of colors and fonts

Small tweaks

- [ ] hexes on package pages are now symmetric not squished

- [ ] jQuery upgrade

- [ ] improved RSS feed handling
