### ISSUE TITLE
New category for blog posts: "roundup"

### ISSUE THREAD

**Issue by juliasilge** [rstudio/hugo-graphite#67]
Hello! 👋 

In tidyverse/tidyverse.org#505 we have the first of a new series of "roundup" blog posts. To quote from the post:

> We plan to begin **regular updates** every three or four months here on the tidyverse blog summarizing what's happening lately in the tidymodels ecosystem overall, as well continuing the focused blog posts on more major new features that we've always written.

We got a suggestion to make a new category for these posts. The category itself is created if I use it, but it looks like we [need a new SVG in the theme](https://github.com/tidyverse/tidyverse.org/tree/master/themes/hugo-graphite/static/css/images).

The two suggestions we have so far are a [summary icon](https://commons.wikimedia.org/wiki/File:Summary_icon.svg) or maybe a [spiral](https://commons.wikimedia.org/wiki/File:Black_bold_spiral.svg). Thoughts?

Ideally we would get this blog post published before the end of the month. Do you think we should wait on this new SVG? Or just publish under another category?

**Comment by dcossyleon** [comment]
What about this SVG? Still for summarizing but has less similarity to the hamburger menu icon: https://material.io/resources/icons/?search=summary&icon=summarize&style=baseline

**Comment by juliasilge** [comment]
I like it! 🙌 @batpigandme what do you think?

**Comment by batpigandme** [comment]
Perfection! 
Dead re. 🍔  menu

**Comment by juliasilge** [comment]
> Ideally we would get this blog post published before the end of the month. Do you think we should wait on this new SVG? Or just publish under another category?

What do you all think about this issue of timing? Should we wait for this new "roundup" category? Or just publish the initial post without it. We are starting to now have tidymodels blog post in the queue that should publish _after_ that first post.

**Comment by batpigandme** [comment]
@dcossyleon do you have the time to "graphite"-ify it? If not, I don't think it's the end of the world to just publish it, Julia.

**Comment by dcossyleon** [comment]
Yeah, I don't think that timeline is a problem :-) I'll make the necessary changes in graphite tonight. Then all that will be left is updating the theme with `blogdown::install_theme("rstudio/hugo-graphite")` -- is that right @apreshill?

**Comment by apreshill** [comment]
Yes, on tidyverse.org, run:
```
blogdown::install_theme("rstudio/hugo-graphite", update_config=FALSE, force=TRUE)
```

I would only commit the files changed here if possible- there was some work in an RSS layout file that hasn't been merged in yet on tidyverse.org that I'm rethinking (sorry)
