### ISSUE TITLE
Have page <title> element reflect individual page titles

### ISSUE THREAD

**Issue by batpigandme** [rstudio/hugo-graphite#70]
On the tidyverse blog (and site as a whole) it seems that the `<title></title>` element (i.e. what shows up in the tab in a browser) shows up as "Tidyverse" for all pages and blog articles. The `og:title` property in the metadata is the article title, so it works fine in previews, but not in tabs. See, e.g., the difference between the tab for a tidyverse [blog post](https://www.tidyverse.org/blog/2021/03/tidymodels-2021-q1/) vs. a [specific pag](https://dplyr.tidyverse.org/articles/dplyr.html)e of a pkgdown site:
![tidyverse blog post with title element not reflecting article title](https://user-images.githubusercontent.com/831732/118276910-70242880-b485-11eb-87b9-27613358e485.png)
![Introduction to dplyr page with title element reflecting the specific page name](https://user-images.githubusercontent.com/831732/118276999-87631600-b485-11eb-8739-a8f635deabfb.png)

Assuming this is a we'd want to make for any sites using the theme, would this go in the header partial? Happy to help, just want to make I'm working in the right direction.

cc @apreshill @hadley

**Comment by apreshill** [comment]
Hi- I meant to do the fix in a branch...but pushed to master so it is there now :) https://github.com/rstudio/hugo-graphite/commit/a896bfef7c539496d2f391742a2275f815c3c690
